### ISSUE TITLE
kubectx resets - deletes user details- when switching contexts

### ISSUE THREAD

**Issue by javapapo** [ahmetb/kubectx#137]
Maybe I am missing something. I am AWS EKS user,and in order to talk to the cluster you need to tunnel your kubectl calls to the aws-iam-authenticator (aka Heptio)

Usually in order to do this you need to change your kube_config a bit and the user will look like this

```yaml
users:
- name: arn:aws:eks:eu-west-1:XXXXXXX:cluster/eks1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - EKS1
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: <AWS_PROFILE>
```

This is usually done with the aws-cli which adds this info to your kube_config

```bash
aws --region eu-west-1 --profile <XXX> eks update-kubeconfig --name EKS1
```

Now in my kube_config I have 3 or more contexts. 2 of them are not EKS and they don't use the aws_authenticator (they have the user/password and certificate) and the third one is the EKS one.

When I use kubectx to swithc between the 2 non EKS cluster contextes to the EKS one..the user section of kube_config for the EKS cluster gets nuked

```yaml
users:
- name: arn:aws:eks:eu-west-1:XXXX:cluster/eks1
  user: {}
```
