### ISSUE TITLE
kubens doesn't work on Windows with context names with colon (:) like EKS clusters

### ISSUE THREAD

**Issue by EvgeniGordeev** [ahmetb/kubectx#230]
### Environment 
Windows 10
EKS 1.16
GO binaries for Windows from https://github.com/ahmetb/kubectx/releases/tag/v0.9.0

EKS clusters have long context names - arn:aws:eks:<region>:<account_id>:cluster/<eks_name> - with the characters not allowed in file names on [Windows](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names/31976060#31976060). 

`kubectx` works, `kubens` doesn't: 

```bash
$ kubectx arn:aws:eks:<region>:<account_id>:cluster/test-3
[32m:heavy_check_mark: [0mSwitched to context "arn:aws:eks:<region>:<account_id>:cluster/test-3".
$ kubens dev
[31;1merror: [0mfailed to load previous namespace from file: open <USER_FOLDER>\.kube\kubens\arn:aws:eks:<region>:<account_id>:cluster\test-3: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by ahmetb** [comment]
🤔 yeah `:` characters are not allowed on Windows filenames. Also the problem shouldn't be specific to Go implementation (though, WSL which can run bash probably supports `:` just fine).

Is this the Kubeconfig AWS gives you by default, or is it manually crafted to have `:` in the names?

**Comment by EvgeniGordeev** [comment]
it's the default kubeconfig provided by [AWS CLI command](https://docs.aws.amazon.com/cli/latest/reference/eks/update-kubeconfig.html) which looks like : 

```yaml

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://<hash>.<hash>.<region>.eks.amazonaws.com
  name: arn:aws:eks:<region>:<account_id>:cluster/<eks_name>
contexts:
- context:
    cluster: arn:aws:eks:<region>:<account_id>:cluster/<eks_name>
    namespace: dev
    user: arn:aws:eks:<region>:<account_id>:cluster/<eks_name>
  name: arn:aws:eks:<region>:<account_id>:cluster/<eks_name>
current-context: arn:aws:eks:<region>:<account_id>:cluster/<eks_name>
kind: Config
preferences: {}
users:
- name: arn:aws:eks:<region>:<account_id>:cluster/<eks_name>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - <region>
      - eks
      - get-token
      - --cluster-name
      - <eks_name>
      command: aws
      env: null
```
