### ISSUE TITLE
[Go] kubens error with Azure auth provider: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DerGary** [ahmetb/kubectx#240]
When I try to use kubens it just prints an error:

```
C:\>kubens
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1115a97]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).storeTokenInCfg(0xc00023bdc0, 0xc000592000, 0xd, 0xc000592000)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:276 +0x397
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).Token(0xc00023bdc0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:206 +0x2b3
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureRoundTripper).RoundTrip(0xc0003533c0, 0xc0001e0600, 0x13e131d, 0xa, 0xc000375d80)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:125 +0x88
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0003533e0, 0xc0001e0500, 0xc0003533e0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/transport/round_trippers.go:159 +0x1c7
net/http.send(0xc0001e0500, 0x1584520, 0xc0003533e0, 0x0, 0x0, 0x0, 0xc0000cadd8, 0x2030000, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc00033f3e0, 0xc0001e0500, 0x0, 0x0, 0x0, 0xc0000cadd8, 0x0, 0x1, 0xc000375a20)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc00033f3e0, 0xc0001e0500, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:567
k8s.io/client-go/rest.(*Request).request(0xc00026e960, 0xc0000c7830, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:801 +0x3f0
k8s.io/client-go/rest.(*Request).Do(0xc00026e960, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:873 +0xdf
k8s.io/client-go/kubernetes/typed/core/v1.(*namespaces).List(0xc00036ab50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/typed/core/v1/namespace.go:86 +0x17e
main.queryNamespaces(0xc0000c7e68, 0xc000281408, 0x7, 0xc000281188, 0x7, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:73 +0x2b7
main.ListOp.Run(0x1584900, 0xc0000ca008, 0x1584900, 0xc0000ca010, 0x0, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:37 +0x209
main.main()
        /home/runner/work/kubectx/kubectx/cmd/kubens/main.go:20 +0x10f
```

kubectl and kubectx work.
they all are located in the same folder that is also added to the path.

using newest versions of kubectl kubectx and kubens.
OS: Windows 10 1809

**Comment by ahmetb** [comment]
This seems to be a duplicate of #232. Sadly, I have no bandwidth to resolve this, and it seems like the pointer error is coming from Azure’s libraries.

My theory is that this is because we parse kubeconfig from an in-memory byte array (as opposed to parsing from a file); so some systems like azure client-go auth plugin bork out because they cannot find the kubeconfig file path.

**This will be addressed in #229.**

For my record: Does this always happen? Or does it go away when azure successfully fetches a token once (and writes to kubeconfig) when you run something like `kubectl get nodes` and then run `kubens`?

**Comment by DerGary** [comment]
@ahmetb 
Thanks for your fast reply.

I just tried running `kubectl get nodes` and directly after that `kubens` and `kubens` returned the same error as described above. So far I did always get this error message when I run `kubens`

**Comment by manoharant** [comment]
@ahmetb Do you know when will this issue would be fixed? kubectx and kubens is now my favourite options to manage the k8s cluster and without kubens working, it is difficult for changeing the namespaces often.

**Comment by ahmetb** [comment]
@manoharant I currently can’t give an estimate. It seems like we need to debug the client-go repo as that’s where the error is coming from. It seems the azure auth driver isn’t written properly. But we’ll change a few things about how we do read the kubeconfig file, and it might fix that.

**Comment by manoharant** [comment]
@ahmetb 
This is working fine when you try to get the credential from azure with --admin option
**az aks get-credentials --resource-group myResourceGroup --name myAKSCluster --admin**

**Comment by ahmetb** [comment]
I don’t know what that means. Why does it work?

**Comment by manoharant** [comment]
It is the command to get the credential from Azure AKS cluster to local k8s config and after running the above command with --admin option, latest kubens is working fine without the above issue.

**Comment by ahmetb** [comment]
I get that. But why? :)

**Comment by AlbertoPeon** [comment]
Hi @ahmetb, 
First of all, thanks a lot for `kubectx` and `kubens`, they are great tools!

I have also encountered this issue when using AKS and I can confirmed what @manoharant said, it is working with the `--admin` flag. The only difference of obtaining the kubeconfig with `az aks get-credentials` using `--admin` is that you [get admin credentials](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials) that will skip the RBAC check when running a `kubectl` for the first time.

In practice, this results in a different context YAML format.

Without `--admin` (and once passed the RBAC check):  

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: '...'
    server: '...'
  name: mycluster
contexts:
- context:
    cluster: mycluster
    user: myUser
  name: mycontext
current-context: mycontext
kind: Config
preferences: {}
users:
- name: myUser
  user:
    auth-provider:
      config:
        access-token: '...'
        apiserver-id: '...'
        client-id: '...'
        environment: '...'
        expires-in: "..."
        expires-on: "..."
        refresh-token: '...'
        tenant-id: '...'
      name: '...'
```

With `--admin`:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: '...'
    server: '...'
  name: mycluster
contexts:
- context:
    cluster: mycluster
    user: myAdminUser
  name: mycontext
current-context: mycontext
kind: Config
preferences: {}
users:
- name: myAdminUser
  user:
    client-certificate-data: '...'
    client-key-data: '...'
    token: '...'
```

Perhaps the parsing of the library does not support the Azure specific fields? Thanks!
