### ISSUE TITLE
kubens is not working if tls-server-name is different than server

### ISSUE THREAD

**Issue by quickstar** [ahmetb/kubectx#257]
Hi

In my setup the tls-server-name differs from the actual server url.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1C.....
    server: https://k8api.somedomain.com:6443
    tls-server-name: k8api.local
  name: prod-cluster
```
If I now run kubens e get the following error:

`error: could not list namespaces (is the cluster accessible?): failed to list namespaces from k8s API: Get "https://k8api.somedomain.com:6443/api/v1/namespaces?limit=500": x509: certificate is valid for k8api-01.local, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, k8api.local, not k8api.somedomain.com`

if I run `kubectl get ns` everthing works just fine.
I use the Go binaries on a windows host.

**Comment by ahmetb** [comment]
I suspect this is an issue with the http://git.k8s.io/client-go/.
I might take a look later.

**Comment by quickstar** [comment]
> 
> 
> I suspect this is an issue with the http://git.k8s.io/client-go/.
> I might take a look later.

That would be nice! I really appreciate your tool, it's such a time saver :-)

**Comment by quickstar** [comment]
Hi @ahmetb 
Any progress on this?

**Comment by ahmetb** [comment]
I still think this is an issue in client-go repository. We initialize a kubernetes API client with the method client-go provides:

https://github.com/ahmetb/kubectx/blob/8c323c56539e0d65ce0a596f803bd7c27e1d57c9/cmd/kubens/list.go#L87-L90

so if it doesn't take the `tls-server-name` parameter in your kubeconfig, that's the bug. I don't think it's something I should be fixing in this repo.

**Comment by FabioAntunes** [comment]
Hey @ahmetb apologies for commenting on a closed issue, but this is still an issue today. Is there any way this could be mitigated?

**Comment by ahmetb** [comment]
Hi @FabioAntunes since a lot of users don't hit this, I'm gonna need some debugging from you. I don't know what makes this situation go away in kubectl, and we're using the recommended client library here.

**Comment by FabioAntunes** [comment]
Hi @ahmetb apologies for not answering sooner was on holiday. I'm more than happy to provide any info necessary.

We use an SDP(teleport) to provide access to our cluster.

The config looks something like this:

```
clusters:
- cluster:
    certificate-authority-data: CERT_DATA
    server: https://domain.teleport.sh:443
    tls-server-name: kube.domain.teleport.sh
  name: domain.teleport.sh
  
contexts:
- context:
    cluster: domain.teleport.sh
    user: cluster-name
  name: cluster-name
```
