### ISSUE TITLE
`kubens` fails with `invalid apiVersion "client.authentication.k8s.io/v1"` but `kubectl` works normally

### ISSUE THREAD

**Issue by felipecrs** [ahmetb/kubectx#391]
As the title says, kubens doesn't work but kubectl does. I wonder what's wrong.

```console
❯ kubens --version
0.9.4
❯ kubens default
error: failed to query if namespace exists (is cluster accessible?): failed to initialize k8s REST client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1"
❯ kubectl version --short
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.25.3
❯ kubectl get namespaces
NAME                          STATUS   AGE
cattle-fleet-system           Active   146d
cattle-impersonation-system   Active   146d
cattle-system                 Active   146d
cis-operator-system           Active   146d
cluster-crds                  Active   50d
default                       Active   146d
gatekeeper-system             Active   146d
ingress-nginx                 Active   146d
kube-node-lease               Active   146d
kube-public                   Active   146d
kube-system                   Active   146d
local                         Active   146d
```

Here is how my kubeconfig looks like:

```yaml
apiVersion: v1
kind: Config
users:
  - name: user # redacted
    user:
      exec:
        command: "internal-authentation-binary" # redacted
        apiVersion: "client.authentication.k8s.io/v1"
        args:
          - "kubeconfig"
          - "auth"
        interactiveMode: IfAvailable
clusters:
  - name: cluster-name # redacted
    cluster:
      server: cluster-url # redacted
      certificate-authority-data: "" # redacted
contexts:
  - name: cluster-name # redacted
    context:
      cluster: cluster-name # redacted
      user: user # redacted
current-context: cluster-name # redacted

```
