### ISSUE TITLE
kubens not working with in-cluster config

### ISSUE THREAD

**Issue by SQLExceptionPhil** [ahmetb/kubectx#400]
When using kubens with a ServiceAccount from within the cluster it isn't working. 
From what I saw it comes from how the config is loaded. When using the kubectl tool it uses the in-cluster configuration and given a small and incomplete config file it is also possible to change the namespace:

```yaml
apiVersion: v1
clusters: null
contexts: 
  - context: 
       namespace: my-namespace
    name: my-context
current-context: "mycontext"
kind: Config
preferences: {}
users: null
```
I think it should be possible to use the old bash version of kubens with this setup - but not the new golang version.
