### ISSUE TITLE
suggestion / feature request: support yaml anchors and aliases

### ISSUE THREAD

**Issue by joelcox22** [ahmetb/kubectx#436]
Currently using Kubectx removes yaml [anchors and aliases](https://yaml.org/spec/1.2.2/#3222-anchors-and-aliases) from kubeconfig files

For example, if you have a kubectx that looks like this, where you're using the same certificate authority data for multiple cluster definitions, and you define the certificate authority data once, and reference it from the other cluster definitions, when you use kubectx to switch to a different cluster, all the references will be replaced with the concrete value, and aliases/references removed.

---

A complete example - save the following as your kubeconfig file

```
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: &cadata REDACTED
      server: https://10.0.0.2:6443
    name: cluster1
  - cluster:
      certificate-authority-data: *cadata
      server: https://10.0.0.3:6443
    name: cluster2
  - cluster:
      certificate-authority-data: *cadata
      server: https://10.0.0.4:6443
    name: cluster3
contexts:
  - context:
      cluster: cluster1
      namespace: default
      user: my-user
    name: cluster1
  - context:
      cluster: cluster2
      namespace: default
      user: my-user
    name: cluster2
  - context:
      cluster: cluster3
      namespace: default
      user: my-user
    name: cluster3
current-context: cluster1
kind: Config
preferences: {}
users:
  - name: my-user
    user:
      client-certificate-data: REDACTED
      client-key-data: REDACTED
```

Then run `kubectx cluster2`

If you then look at the kubeconfig file, it will now be

```diff
apiVersion: v1
clusters:
  - cluster:
-      certificate-authority-data: &cadata REDACTED
+      certificate-authority-data: REDACTED
      server: https://10.0.0.2:6443
    name: cluster1
  - cluster:
+      certificate-authority-data: REDACTED
      server: https://10.0.0.3:6443
    name: cluster2
  - cluster:
+      certificate-authority-data: REDACTED
      server: https://10.0.0.4:6443
    name: cluster3
contexts:
  - context:
      cluster: cluster1
      namespace: default
      user: my-user
    name: cluster1
  - context:
      cluster: cluster2
      namespace: default
      user: my-user
    name: cluster2
  - context:
      cluster: cluster3
      namespace: default
      user: my-user
    name: cluster3
current-context: cluster1
kind: Config
preferences: {}
users:
  - name: my-user
    user:
      client-certificate-data: REDACTED
      client-key-data: REDACTED
```

Suggestion: kubectx should ideally retain yaml anchors and aliases 😄
