### ISSUE TITLE
Kubectx switching removes heptio user from config file

### ISSUE THREAD

**Issue by easiestripes** [ahmetb/kubectx#63]
Please let me know if this isn't a bug and I'm just doing something wrong, but I haven't been able to find any info related to this.

So for AWS EKS clusters, Amazon's guide (https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html) tells you to use their heptio authenticator and that your .kube/config should look like:
```
apiVersion: v1
clusters:
- cluster:
    server: <endpoint-url>
    certificate-authority-data: <base64-encoded-ca-cert>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "<cluster-name>"
        # - "-r"
        # - "<role-arn>"
      # env:
        # - name: AWS_PROFILE
        #   value: "<aws-profile>"
```

But every time I switch contexts using `kubectx` it modifies the .kube/config to:
```
apiVersion: v1
clusters:
- cluster:
    server: <endpoint-url>
    certificate-authority-data: <base64-encoded-ca-cert>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user: {}
```

So it removes the entire heptio auth user part of the config so I have to re-add it manually each time to access my cluster after switching from another context.
